export default {
    // Blues
    "blue": "#2970FF",
    "blue-dark": "#1A46A9",
    "blue-darkest": "#091440",
    "blue-zodiac": "#18234D",
    // Greys
    "grey-jet": "#5F6683",
    "grey-light": "#E4E6EA",
    "grey": "#787F98",
    "grey-regent": "#9196AA",
    "grey-rhino-light": "#3F486B",
    "grey-rhino": "#2B355B",
    "grey-smokey": "#707070",
    // White
    "white": "#fff",
    // Font
    "font-color": "var(--white)",
    "font-size-sm": "8px",
    "font-size-md": "13px",
    "font-size-lg": "15px",
    "font-size-xl": "21px",
    // Layout
    "bg-color": "var(--blue-darkest)",
    // Header
    "header-bg-color": "var(--bg-color)",
    // Footer
    "footer-bg-color": "var(--bg-color)"
};